services:
  rtb4j-reset:
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
      - HOST=0.0.0.0
      - PORT=8080
      - PUBLIC_HOST=localhost:8080
      - REDIS_BID_CACHE=redis://redis:6379
      - DEV_SKIP_BIDDER_AUCTIONS=false
      - DEV_SKIP_FORCE_BIDDER=false
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
