services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - JAVA_OPTS=-Xms512m -Xmx4096m
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317
    networks:
      - app-network
    ports:
      - "8080:8080"
    restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy  # Map the config.alloy file
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317
    networks:
      - app-network
    command: run /etc/alloy/config.alloy

networks:
  app-network:
    driver: bridge
